# Generated by Django 5.0.1 on 2024-02-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=50, verbose_name='fname')),
                ('l_name', models.CharField(max_length=50, verbose_name='lname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('password', models.EmailField(max_length=254, verbose_name='email')),
                ('password1', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
    ]
