# Generated by Django 5.0.1 on 2024-02-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='password',
            field=models.CharField(max_length=254, verbose_name='pass1'),
        ),
        migrations.AlterField(
            model_name='log',
            name='password1',
            field=models.CharField(max_length=254, verbose_name='pass2'),
        ),
    ]
