# Generated by Django 5.0.1 on 2024-02-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_log',
            name='pass2',
        ),
    ]
